config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :products, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :rentings, only: [ :create, :destroy, :edit, :update]
  end
  resources :rentings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORY = %w(Art Bags Clothes Jewelry Shoes)
  belongs_to :user
  has_many :rentings, dependent: :destroy
  has_one_attached :photo
  validates :photo, presence: true
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :rentings, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  # include Pundit::Authorization
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @rentings = Renting.all
    @products = policy_scope(Product)
  end

  def show
    @products = policy_scope(Product)
    @renting = Renting.new
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @user = current_user
    authorize @product
    @product.user = @user
    authorize @product
    if @product.save
      redirect_to product_path(@product), notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully deleted.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:description, :price, :condition, :photo, :category)
  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  # include Pundit::Authorization
  before_action :set_product, except: [:index, :edit]

  def index
    @rentings = policy_scope(Renting)
    @products = current_user.products

  end

  def show
    @renting = Renting.find(params[:id])
  end

  def create
    @product = Product.find(params[:product_id])
    @renting = Renting.new
    authorize @product
    @renting.product = @product
    @renting.user = current_user
    @renting.status = false
    @renting.save

    redirect_to product_path(@product), notice: 'Reservation was successfully created.'
  end

  def destroy
    @renting = Renting.find(params[:id])
    @renting.destroy
    redirect_to rentings_path, notice: 'Reservation was successfully deleted.'
  end

  # def edit
  #   @renting = Renting.find(params[:id])
  #   authorize @renting
  #   @renting.status = true
  #   @renting.save
  # end

  def update
    @renting = Renting.find(params[:id])
    authorize @renting
    @renting.status = true
    @renting.save
    redirect_to rentings_path, notice: 'Reservation was accepted.'
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
    authorize @product
  end

  def renting_params
    params.require(:renting).permit(:status) # Adjust the permitted attributes as needed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuxuryRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%# <div class="container"> %>
          <%# <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    <%# </div> %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_form.html.erb
<%= simple_form_for(product, html: { multipart: true }) do |f| %>
  <%= f.input :category, collection: Product::CATEGORY, input_html: { class: 'rounded' } %>
  <%= f.input :condition, input_html: { class: 'rounded' } %>
  <%= f.input :description, maxlength: 70, input_html: { class: 'rounded' } %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file, input_html: { class: 'rounded', id: "photo-input" }, label: '<i class="fas fa-download"></i> Photo'.html_safe %>
  <%= f.button :submit, class: "btn btn-primary mt-4 rounded" %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing product</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Show this product", @product %> |
    <%= link_to "Back to products", products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <h2 class="mb-4">Products</h2>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <%= link_to product_path(product) do %> <!-- Adicione esta linha -->
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path product.photo.key %>'); background-size: cover;"></div>
          <% end %> <!-- Adicione esta linha -->
          <div class="card-body">
            <h5 class="card-title"><%= product.description %></h5>
            <p class="card-text"><strong><%= product.price %>€ day</strong></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-between">
  <div class="d-grid gap-2 d-md-flex mb-5 justify-content-md-end">
    <button class="btn btn-primary rounded" type="button">
      <% if policy(Product).new? %>
        <%= link_to 'Add New Product', new_product_path, class: 'btn btn-primary rounded' %>
      <% end %>
    </button>
  </div>
  <div class="d-grid gap-2 d-md-flex mb-5 justify-content-md-start">
    <button class="btn btn-primary rounded" type="button">
      <% if policy(Product).new? %>
        <%= link_to 'Your Rentings', rentings_path, class: 'btn btn-primary rounded' %>
      <% end %>
    </button>
  </div>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h2>Welcome</h2>
  <br>
  <h5>Tell us more about what do you want to rent:</h5>

  <%= render 'form', product: @product %>
  <br>
  <div class="row justify-content-between">
      <div class="col-md-6 mt-0 mb-2 text-right">
          <%= link_to products_path do %>
            <div class="btn btn-primary"> Back </div>
            <% end %>
      </div>
  </div>
</div>

app/views/products/show.html.erb
<h2 class="mb-4">Products</h2>
<div class="row">

    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @product.photo.key %>'); background-size: cover;"></div>
        <div class="card-body">
          <h5 class="card-title"><%= @product.description %></h5>
          <p class="card-text"><strong><%= @product.price %>€ day</strong></p>
        </div>
      </div>
    </div>
</div>

<div class="col-md-8 mb-4">
  <div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <%= link_to products_path do %>
      <div class="btn btn-primary"> Back </div>
    <% end %>

    <% if policy(@product).edit?  %>
      <%= link_to edit_product_path do %>
        <div class="btn btn-primary"> Edit </div>
      <% end %>
    <% end  %>

    <% unless policy(@product).edit? %>
        <%= link_to  product_rentings_path(@product, @renting), data: {turbo_method: :post } do %>
          <div class="btn btn-success"> Book this product </div>
        <% end %>
      <% end %>




    <% if policy(@product).destroy?  %>
      <%= link_to product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <div class="btn btn-danger"> Delete </div>
      <% end %>
    <% end  %>
  </div>
  <% if notice %>
    <%= notice %>
  <% end %>
</div>

app/views/rentings/index.html.erb
<div class="container">
  <h2 class="mb-4">Your rentings:</h2>
  <div class="row">
    <% if @rentings.any? %>
      <% @rentings.each do |renting| %>
        <% if renting.status? %></p>
          <p>Your item is booked!</p>
        <% else %>
          <p>Waiting for confirmation...</p>
        <% end %>
        <p><%= cl_image_tag renting.product.photo.key,  height: 300, width: 400 %></p>
      <% end %>
    <% end %>
  </div>

  <% if @products.any?%>
    <% @products.each do |product| %>
      <% if product.rentings.any? %>
      <% product.rentings.each do |renting| %>
      <% unless renting.status  %>
        <%= cl_image_tag product.photo.key,  height: 300, width: 400 %>
      <%= link_to "Confirm", product_renting_path(product, renting), data: { turbo_confirm: "Are you sure?", turbo_method: :patch}, class: 'btn btn-primary' %>
      <%= link_to product_renting_path(product, renting), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <div class="btn btn-danger"> Delete </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <%end %>
  <% end %>
</div>

app/views/rentings/new.html.erb
<h1>New reservation</h1>

<%= render 'form', renting: @renting %>

<%= link_to 'back', product_path(@product) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close rounded" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close rounded" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at SmartRent
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lr">
  <div class="container-fluid mt-2px d-flex align-items-center">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.svg", class: "logo-image" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar user-photo", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>